services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: farm-hub
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - farmhub-network
  

  db:
    image: postgres:15
    container_name: farm-hub-db
    environment:
      - POSTGRES_USER=farmhub
      - POSTGRES_PASSWORD=FarmhubHehe
      - POSTGRES_DB=farmhub
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U farmhub"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - farmhub-network
  
  ngrok:
    image: ngrok/ngrok:latest
    container_name: farmhub-ngrok
    command:
      - start
      - --all
      - --config
      - /etc/ngrok/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok/ngrok.yml
      - ngrok_data:/etc/ngrok
    ports:
      - "4040:4040"  
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - farmhub-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: farm-hub-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - farmhub-network


volumes:
  postgres_data:
  ngrok_data:
  qdrant_data:

networks:
  farmhub-network:
    driver: bridge